services:
  app:
    build: .  # Acá lee el dockerfile
    ports:
      - "5002:5000"
    #environment:
    #  - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    #  - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./output:/app/output  # Persistencia de archivos
